"""
Extended question bank for mock interviews - 24 questions per role.
These are combined with ROLE_QUESTIONS from routes.py to provide variety.
"""

EXTENDED_ROLE_QUESTIONS = {
    'frontend-developer': [
        'How do you approach performance profiling for a slow-loading React application? Walk through your debugging process.',
        'Explain your strategy for implementing authentication and protected routes in a single-page application.',
        'What is your approach to CSS architecture in a large team? How do you prevent style conflicts?',
        'How do you implement real-time data updates in a frontend application without WebSockets?',
        'Describe how you would build a reusable component library that multiple teams can use.',
        'How do you handle browser caching strategies for static assets in a production frontend app?',
        'Walk me through implementing internationalization (i18n) in a multi-language web application.',
        'How do you ensure your frontend application is secure against XSS and CSRF attacks?',
        'Describe your approach to implementing infinite scroll or virtual scrolling for large datasets.',
        'How would you migrate a legacy application from jQuery to a modern framework without breaking existing features?',
        'Explain how you handle form validation with complex business rules that span multiple fields.',
        'How do you implement A/B testing in a frontend application while maintaining clean code?',
    ],
    'backend-developer': [
        'How would you design a distributed caching strategy for a high-traffic API?',
        'Explain your approach to implementing graceful degradation when a third-party service is down.',
        'How do you handle database connection pooling and prevent connection leaks in production?',
        'Describe how you would implement a webhook system that reliably delivers events to external services.',
        'How do you approach database indexing strategy when queries are getting slower?',
        'Walk me through implementing an idempotent API to handle duplicate requests safely.',
        'How would you design a multi-tenant database architecture with data isolation guarantees?',
        'Explain your strategy for handling file uploads that might be gigabytes in size.',
        'How do you implement feature flags in a backend system for gradual rollouts?',
        'Describe how you would build an API that supports both REST and GraphQL clients.',
        'How do you handle time zones and datetime operations in a global application?',
        'Explain your approach to implementing audit logging for compliance requirements.',
    ],
    'fullstack-developer': [
        'How do you decide between client-side and server-side rendering for different pages in an application?',
        'Describe your approach to implementing real-time collaboration features like Google Docs.',
        'How would you architect a system that needs to handle both web and mobile app clients?',
        'Explain how you manage database schema changes across frontend, backend, and mobile apps.',
        'How do you implement end-to-end type safety from database to frontend UI?',
        'Describe your approach to handling file uploads with progress indicators and resumability.',
        'How would you design an offline-first application that syncs when connectivity returns?',
        'Explain your strategy for managing environment configurations across dev, staging, and production.',
        'How do you implement search functionality with autocomplete, facets, and full-text search?',
        'Describe how you would build a notification system that works across web, email, and push.',
        'How do you handle CORS and API security when building a full-stack application?',
        'Explain your approach to implementing rate limiting across both frontend and backend.',
    ],
    'web-developer': [
        'How do you optimize Core Web Vitals (LCP, FID, CLS) for a production website?',
        'Explain your approach to implementing structured data and schema markup for SEO.',
        'How would you make a website fully accessible to screen reader users?',
        'Describe your process for implementing a responsive email template that works across clients.',
        'How do you handle browser compatibility issues for older browsers like IE11?',
        'Explain your approach to implementing cookie consent and GDPR compliance.',
        'How would you optimize images for the web while maintaining quality?',
        'Describe how you implement lazy loading for images and iframes to improve page speed.',
        'How do you debug and fix layout issues that only appear on mobile devices?',
        'Explain your approach to implementing dark mode that respects user preferences.',
        'How would you build a landing page optimized for conversion rate?',
        'Describe your process for optimizing a website for local search and Google My Business.',
    ],
    'python-developer': [
        'How do you debug memory leaks in a long-running Python application?',
        'Explain your approach to implementing background tasks with Celery or similar tools.',
        'How would you optimize a slow Python script that processes millions of records?',
        'Describe how you handle secrets and configuration management in Python applications.',
        'How do you implement proper logging and monitoring in a production Python service?',
        'Explain your approach to packaging and distributing internal Python libraries.',
        'How would you migrate a Python 2 application to Python 3?',
        'Describe how you handle database migrations in a Django or Flask application.',
        'How do you implement retry logic and circuit breakers for external API calls?',
        'Explain your approach to writing readable and maintainable Python code in a team.',
        'How would you implement caching strategies in a Python web application?',
        'Describe how you handle data validation using Pydantic or similar libraries.',
    ],
    'java-developer': [
        'How do you diagnose and fix memory leaks in a Java application?',
        'Explain your approach to tuning garbage collection for low-latency requirements.',
        'How would you implement distributed tracing across microservices?',
        'Describe how you handle database connection pooling in a high-traffic Java application.',
        'How do you implement proper exception handling and error reporting in Spring Boot?',
        'Explain your approach to writing integration tests for Spring Boot applications.',
        'How would you implement a saga pattern for distributed transactions?',
        'Describe how you handle API versioning in a microservices architecture.',
        'How do you implement circuit breakers and fallback mechanisms using Resilience4j?',
        'Explain your approach to implementing event-driven architecture with Kafka.',
        'How would you migrate a monolith to microservices incrementally?',
        'Describe how you implement API documentation using OpenAPI/Swagger.',
    ],
    'cpp-developer': [
        'How do you detect and prevent undefined behavior in C++ code?',
        'Explain your approach to implementing custom allocators for performance optimization.',
        'How would you design a thread-safe singleton pattern in modern C++?',
        'Describe how you handle cross-platform compilation and platform-specific code.',
        'How do you use constexpr and compile-time programming to improve performance?',
        'Explain your approach to implementing zero-cost abstractions.',
        'How would you optimize cache locality for better performance?',
        'Describe how you handle RAII for complex resource management scenarios.',
        'How do you implement type-safe variant types using std::variant?',
        'Explain your approach to debugging concurrency issues in multithreaded C++ code.',
        'How would you implement a custom memory pool for specific allocation patterns?',
        'Describe how you handle ABI compatibility across different compiler versions.',
    ],
    'mern-stack': [
        'How do you handle state synchronization between MongoDB and React state?',
        'Explain your approach to implementing optimistic updates in a MERN application.',
        'How would you implement role-based access control across the entire MERN stack?',
        'Describe how you handle error boundaries and error logging in a MERN app.',
        'How do you implement server-sent events or long polling as an alternative to WebSockets?',
        'Explain your approach to implementing data validation on both client and server.',
        'How would you structure a MERN monorepo with shared types and utilities?',
        'Describe how you implement email verification and password reset flows.',
        'How do you handle MongoDB schema migrations in a production MERN app?',
        'Explain your approach to implementing search with MongoDB text indexes or Atlas Search.',
        'How would you implement rate limiting and API throttling in Express?',
        'Describe how you handle file storage and CDN integration in a MERN stack.',
    ],
    'ai-engineer': [
        'How do you handle catastrophic forgetting in continual learning scenarios?',
        'Explain your approach to implementing model interpretability and explainability.',
        'How would you design an A/B testing framework for machine learning models?',
        'Describe how you handle data drift detection in production ML systems.',
        'How do you implement real-time inference with low latency requirements?',
        'Explain your approach to implementing federated learning for privacy preservation.',
        'How would you optimize a model for edge deployment with limited compute?',
        'Describe how you handle class imbalance in time series forecasting.',
        'How do you implement model monitoring and alerting in production?',
        'Explain your approach to implementing AutoML pipelines for feature engineering.',
        'How would you design a recommendation system that handles cold start problems?',
        'Describe how you implement active learning to reduce labeling costs.',
    ],
    'data-analyst': [
        'How do you validate data quality before including it in analysis?',
        'Explain your approach to creating executive dashboards that drive decision-making.',
        'How would you analyze seasonality and trends in time series business data?',
        'Describe how you handle slowly changing dimensions in data warehouses.',
        'How do you implement automated data quality checks and alerts?',
        'Explain your approach to customer lifetime value (LTV) analysis.',
        'How would you design and analyze a pricing experiment?',
        'Describe how you handle attribution modeling for marketing campaigns.',
        'How do you implement cohort retention analysis for a subscription business?',
        'Explain your approach to building predictive models as a data analyst.',
        'How would you analyze and present user behavior funnels to stakeholders?',
        'Describe how you implement RFM (Recency, Frequency, Monetary) analysis.',
    ],
    'devops-engineer': [
        'How do you implement zero-downtime deployments for a production service?',
        'Explain your approach to implementing disaster recovery with automated failover.',
        'How would you design a multi-region, multi-cloud infrastructure?',
        'Describe how you implement infrastructure drift detection and remediation.',
        'How do you handle secret rotation in a microservices environment?',
        'Explain your approach to implementing chaos engineering for resilience testing.',
        'How would you optimize cloud costs without sacrificing performance?',
        'Describe how you implement GitOps workflows with automated deployments.',
        'How do you handle database backups and point-in-time recovery?',
        'Explain your approach to implementing compliance and security scanning in CI/CD.',
        'How would you design a self-healing infrastructure?',
        'Describe how you implement multi-tenant isolation in Kubernetes.',
    ],
    'javascript-developer': [
        'How do you handle circular dependencies in JavaScript modules?',
        'Explain your approach to implementing memoization for expensive computations.',
        'How would you implement a pubsub pattern in vanilla JavaScript?',
        'Describe how you handle timezones and date manipulation in JavaScript.',
        'How do you implement debouncing and throttling for performance optimization?',
        'Explain your approach to implementing deep cloning of complex objects.',
        'How would you implement a virtual DOM from scratch?',
        'Describe how you handle CORS preflight requests in a JavaScript application.',
        'How do you implement service workers for offline functionality?',
        'Explain your approach to implementing web workers for CPU-intensive tasks.',
        'How would you implement a custom event emitter with type safety?',
        'Describe how you handle memory leaks caused by event listeners.',
    ],
    'react-developer': [
        'How do you prevent prop drilling in deeply nested component trees?',
        'Explain your approach to implementing infinite scroll with React Query or SWR.',
        'How would you optimize re-renders in a large form with many inputs?',
        'Describe how you implement drag-and-drop functionality in React.',
        'How do you handle authentication state and token refresh in React?',
        'Explain your approach to implementing a wizard/multi-step form in React.',
        'How would you implement undo/redo functionality in a React application?',
        'Describe how you handle real-time updates with WebSockets in React.',
        'How do you implement SSR data prefetching with Next.js?',
        'Explain your approach to implementing micro-frontends with React.',
        'How would you implement a design system with reusable React components?',
        'Describe how you handle focus management and keyboard navigation for accessibility.',
    ],
    'mean-stack': [
        'How do you implement JWT refresh tokens securely in a MEAN stack?',
        'Explain your approach to implementing server-side pagination with Angular and Express.',
        'How would you handle file uploads with progress tracking across the MEAN stack?',
        'Describe how you implement role-based UI rendering in Angular.',
        'How do you handle MongoDB transaction management in complex workflows?',
        'Explain your approach to implementing lazy loading routes in Angular.',
        'How would you implement caching strategies across Angular, Express, and MongoDB?',
        'Describe how you handle environment-specific configurations in a MEAN app.',
        'How do you implement logging and error tracking across the MEAN stack?',
        'Explain your approach to implementing API mocking for frontend development.',
        'How would you implement internationalization across the entire MEAN stack?',
        'Describe how you handle database seeding and fixtures for testing.',
    ],
    'nodejs-developer': [
        'How do you handle backpressure in Node.js streams?',
        'Explain your approach to implementing graceful shutdown in a Node.js application.',
        'How would you debug a memory leak in a production Node.js service?',
        'Describe how you implement worker threads for CPU-intensive tasks.',
        'How do you handle uncaught exceptions and unhandled promise rejections?',
        'Explain your approach to implementing request tracing across microservices.',
        'How would you implement session management in a stateless Node.js API?',
        'Describe how you handle database connection pooling with PostgreSQL or MongoDB.',
        'How do you implement HTTP/2 and server push in a Node.js application?',
        'Explain your approach to implementing distributed rate limiting with Redis.',
        'How would you implement a job queue with retries and dead-letter queues?',
        'Describe how you handle timezone conversions and scheduled tasks in Node.js.',
    ],
    'data-scientist': [
        'How do you handle missing data imputation in a way that preserves relationships?',
        'Explain your approach to implementing ensemble methods for model improvement.',
        'How would you detect and handle outliers in a dataset?',
        'Describe how you implement stratified sampling for imbalanced datasets.',
        'How do you validate that your model generalizes beyond the training data?',
        'Explain your approach to implementing SHAP or LIME for model explainability.',
        'How would you design experiments to measure causal impact?',
        'Describe how you handle multicollinearity in regression models.',
        'How do you implement time series cross-validation properly?',
        'Explain your approach to implementing anomaly detection algorithms.',
        'How would you build and evaluate a churn prediction model?',
        'Describe how you handle text preprocessing for NLP tasks.',
    ],
    'data-engineer': [
        'How do you implement slowly changing dimensions (SCD) in data warehouses?',
        'Explain your approach to implementing data lineage tracking.',
        'How would you design a lambda architecture for real-time and batch processing?',
        'Describe how you handle late-arriving data in streaming pipelines.',
        'How do you implement idempotent data pipelines?',
        'Explain your approach to implementing data partitioning strategies.',
        'How would you optimize Spark jobs that are running slowly?',
        'Describe how you handle schema mismatches in data integration.',
        'How do you implement data validation and quality metrics?',
        'Explain your approach to implementing incremental data loads.',
        'How would you design a medallion architecture (bronze/silver/gold)?',
        'Describe how you handle PII data masking and encryption.',
    ],
    'cloud-engineer': [
        'How do you implement least-privilege IAM policies at scale?',
        'Explain your approach to implementing cost allocation and chargeback.',
        'How would you design a landing zone for a multi-account AWS organization?',
        'Describe how you implement network segmentation and micro-segmentation.',
        'How do you handle DNS and service discovery in a cloud environment?',
        'Explain your approach to implementing compliance as code.',
        'How would you design a hybrid cloud connectivity solution?',
        'Describe how you implement cloud resource tagging strategies.',
        'How do you handle cloud vendor lock-in concerns?',
        'Explain your approach to implementing FinOps practices.',
        'How would you design a cloud-native backup and recovery strategy?',
        'Describe how you implement infrastructure as code testing and validation.',
    ],
    'mobile-developer': [
        'How do you handle app state restoration after the app is killed by the OS?',
        'Explain your approach to implementing deep linking with universal links.',
        'How would you optimize app startup time and reduce time to interactive?',
        'Describe how you handle background data synchronization efficiently.',
        'How do you implement secure storage for sensitive data on mobile devices?',
        'Explain your approach to implementing app analytics and crash reporting.',
        'How would you handle app versioning and force update logic?',
        'Describe how you implement offline-first architecture with sync conflicts.',
        'How do you optimize battery consumption in location-based apps?',
        'Explain your approach to implementing biometric authentication.',
        'How would you handle different screen densities and aspect ratios?',
        'Describe how you implement app store optimization (ASO) strategies.',
    ],
    'flutter-developer': [
        'How do you handle navigation with complex nested routes in Flutter?',
        'Explain your approach to implementing platform channels for native features.',
        'How would you optimize Flutter app size for production releases?',
        'Describe how you implement background tasks and isolates in Flutter.',
        'How do you handle different screen sizes with responsive layouts?',
        'Explain your approach to implementing custom animations and transitions.',
        'How would you implement internationalization with dynamic locale switching?',
        'Describe how you handle app state persistence across app restarts.',
        'How do you implement code generation with build_runner for productivity?',
        'Explain your approach to implementing accessibility in Flutter apps.',
        'How would you handle version migration for local database schemas?',
        'Describe how you implement flavor-based builds for different environments.',
    ],
    'android-developer': [
        'How do you handle configuration changes without losing state?',
        'Explain your approach to implementing WorkManager for background tasks.',
        'How would you optimize RecyclerView performance for large lists?',
        'Describe how you implement deep linking and app links in Android.',
        'How do you handle memory leaks caused by context references?',
        'Explain your approach to implementing notification channels and importance.',
        'How would you implement data binding with MVVM architecture?',
        'Describe how you handle runtime permissions and permission rationale.',
        'How do you implement ProGuard/R8 rules for proper code obfuscation?',
        'Explain your approach to implementing modular Android apps.',
        'How would you handle multi-module navigation with Navigation Component?',
        'Describe how you implement Android App Bundles for optimized delivery.',
    ],
    'ios-developer': [
        'How do you handle memory management and prevent retain cycles in Swift?',
        'Explain your approach to implementing background app refresh efficiently.',
        'How would you optimize UITableView/UICollectionView scrolling performance?',
        'Describe how you handle universal links and custom URL schemes.',
        'How do you implement keychain services for secure data storage?',
        'Explain your approach to implementing app extensions (widgets, share, etc.).',
        'How would you handle app thinning and on-demand resources?',
        'Describe how you implement proper error handling with Result types.',
        'How do you handle different iOS versions and API availability checks?',
        'Explain your approach to implementing MVVM with Combine framework.',
        'How would you implement continuous integration for iOS apps?',
        'Describe how you handle app review guidelines and rejection scenarios.',
    ],
    'blockchain-developer': [
        'How do you implement gas optimization strategies in Solidity?',
        'Explain your approach to preventing reentrancy attacks in smart contracts.',
        'How would you implement upgradeable smart contracts safely?',
        'Describe how you handle oracle integration for off-chain data.',
        'How do you implement access control patterns in smart contracts?',
        'Explain your approach to implementing multi-signature wallets.',
        'How would you design a token vesting contract with time-based unlocks?',
        'Describe how you handle front-running prevention in DeFi protocols.',
        'How do you implement event logging for blockchain transaction tracking?',
        'Explain your approach to implementing cross-chain bridges.',
        'How would you design a DAO voting mechanism with delegation?',
        'Describe how you handle MEV (Maximal Extractable Value) considerations.',
    ],
    'cybersecurity-engineer': [
        'How do you implement security monitoring for insider threats?',
        'Explain your approach to conducting threat hunting proactively.',
        'How would you design a security operations center (SOC) workflow?',
        'Describe how you handle security incident containment and eradication.',
        'How do you implement security controls for containerized environments?',
        'Explain your approach to implementing data loss prevention (DLP).',
        'How would you conduct a security architecture review for a new system?',
        'Describe how you handle vulnerability prioritization and remediation.',
        'How do you implement security awareness training and phishing simulations?',
        'Explain your approach to implementing endpoint detection and response (EDR).',
        'How would you design a privileged access management (PAM) system?',
        'Describe how you handle security compliance audits and reporting.',
    ],
}
